### ISSUE TITLE
Polymer undefined

### ISSUE THREAD

**Issue by Sinjins** [PolymerElements/generator-polymer-init-custom-build#62] opened 2017-02-22 02:29 UTC
Using the latest instructions/readme, after successfully building using `npm run build`, and then attempting to serve using `polymer serve build/` and browsing to http://localhost:8080, I am getting a '_Polymer is not a function_' in Chrome dev console.  Also noticed that polymer.html is not being loaded/imported in the Network Panel.

**Comment by stramel** [comment] 2017-02-22 03:50
Yeah, I had to modify mine to work more reliably on slower connections.

**Comment by Sinjins** [comment] 2017-02-22 16:47
@stramel so you ran into the same issue, but were able to resolve it?

**Comment by stramel** [comment] 2017-02-22 17:01
@Sinjins This is what I have that was working for me. https://gist.github.com/stramel/315ecb112b4671035dbbbcfd99a9cbdf

**Comment by robdodson** [comment] 2017-02-24 00:43
@sinjins do you have bower installed? Did it create a bower_components directory for you in your project?

**Comment by Sinjins** [comment] 2017-02-24 01:44
Hi @robdodson.  Indeed I do...and it did create a bower_components directory for me in the build directory.  See attached screenshots for further info.

![image](https://cloud.githubusercontent.com/assets/8175537/23286929/752a9c38-f9ef-11e6-939d-29219e356e45.png)

![image](https://cloud.githubusercontent.com/assets/8175537/23286965/910e2d52-f9ef-11e6-822e-0693b09cbf6d.png)

**Comment by jsilvermist** [comment] 2017-02-24 15:19
Do you get the same result if you cd to the build directory before running `polymer serve`?

If you navigate to `build/bower_components/polymer` does `polymer.html` exist there?

**Comment by Sinjins** [comment] 2017-02-24 18:17
Hi @jsilvermist.  Yes build/bower_components/polymer/polymer.html exists.  I had also tried serving from the build directory.  Same result.

**Comment by robdodson** [comment] 2017-02-26 03:17
Could you create a gist of the contents of your `build/src/my-app.html` and share it?

**Comment by robdodson** [comment] 2017-02-26 03:18
Also, just for fun... can you go into the Application panel of Chrome DevTools, click the Clear storage sidebar item, and then click the "Clear site data" button. And try doing a hard refresh of the page?

**Comment by Sinjins** [comment] 2017-02-26 03:45
Hey @robdodson here's a gist for ya:  [my_app.html](https://gist.github.com/Sinjins/c9dc6b745f29e70888265b08880b324f)

I also cleared the site data...no dice!

**Comment by robdodson** [comment] 2017-02-26 08:19
This looks like
https://github.com/PolymerElements/generator-polymer-init-custom-build/issues/58.
Can you make sure you have version 0.8.1 of polymer build installed in your
node_modules? Check your package.json to verify you have the latest. I need
to double check which version is on npm, might need a new publish

**Comment by Sinjins** [comment] 2017-02-26 17:38
@robdodson just updated polymer-build to 0.8.1 (npm package versions shown in screenshot), and ran build again.  Now the build doesn't complete, due to async tasks not completing.  Screenshot attached, as mentioned.

![image](https://cloud.githubusercontent.com/assets/8175537/23342021/46ca4e96-fc07-11e6-8b3f-1f4cec82f55b.png)

**Comment by robdodson** [comment] 2017-02-26 18:05
OK my hunch based on other threads like this is that there's a missing file somewhere. Is this a completely fresh project or have you modified it some?

Can you check all of your html imports and make sure each element imports the dependencies it needs?

Can you also look at your polymer.json and verify that the fragments array contains all of your views?

cc @FredKSchott

**Comment by Sinjins** [comment] 2017-02-26 18:37
@robdodson This is a completely fresh project, and I followed the instructions/readme for generator-polymer-init-custom-build to a 'T'.  The polymer-build/gulp result does not run in the browser when using polymer-build v0.6.0.  When using polymer-build v0.8.1, it doesn't build at all, presumably due to some change in gulp library in how it handles/expects async callbacks?  Just a guess.  This isn't urgent for me at the moment as I've since moved back to using gulp-vulcanize and a manually constructed gulpfile (using gulp.tasks. gulp.parallel, and gulp.series as defined in latest gulp documentation, instead of a top-level promise as used in the gulpfile here).  I just wanted to inform you that the current state of generator-polymer-init-custom-build isn't working based on the instructions provided.

**Comment by robdodson** [comment] 2017-02-26 22:37
I did a fresh install and it seems to be working for me. Just trying to
figure out what the issue is

**Comment by FredKSchott** [comment] 2017-02-28 18:39
Ugh, gulp error handling is the worst.

@Sinjins make sure that you read the [polymer-build CHANGELOG](https://github.com/Polymer/polymer-build/blob/master/CHANGELOG.md) when updating, there are some breaking changes across versions that you will need to account for when updating.

Otherwise, I'm not sure if we're aware of any issues that would have caused build to be broken but succeed in earlier versions and now silently fail in others.

**Comment by Sinjins** [comment] 2017-02-28 19:25
@robdodson @FredKSchott for further troubleshooting, here are additional gists:

[package.json](https://gist.github.com/Sinjins/13b0086cbe61d205078ba8267ab3cd39)
[polymer.json](https://gist.github.com/Sinjins/7477847e031e18ae1443b149da4ab409)

**Comment by gabema** [comment] 2017-03-12 05:36
Running into this same issue (Polymer is not a function). It appears to be a problem becuase I'm assuming Polymer is supposed to be included in my_app but is not.  I didn't modify anything but simply generated a new custom project from template, built it, then attempted to serve the build output.  Could it be platform related? I'm running on windows.

**Comment by robdodson** [comment] 2017-03-12 07:30
It might be. I know in the past there were issues with file paths that contained spaces in them on Windows. I'm traveling at the moment and don't have a PC handy to test. @FredKSchott do you have a windows laptop?

**Comment by gabema** [comment] 2017-03-13 05:30
It does seem to be Windows platform specific.  I tested on Ubuntu and the custom project template was able to generate, build, and serve properly. Need to be able to build on windows though because I was hoping to run the gulp build command in azure to generate the output post deploy.

**Comment by FredKSchott** [comment] 2017-03-13 21:39
Hmm okay, let me dust off my Windows machine and dig into this. I'm surprised it hasn't been reported in the polymer-build issue tracker, I wonder if it's something special in this project or this gulpfile that causes it to break.

**Comment by CodeBaboon** [comment] 2017-03-20 17:28
Also running on Windows and also hitting this issue trying to serve output generated by the gulp file.

**Comment by CodeBaboon** [comment] 2017-03-20 20:08
I was able to resolve this issue by:

- updating global polymer-cli to `v0.18.0-pre.13`
- updating the `polymer-build` reference in my project to `0.8.4`
- updating the contents of my gulpfile.js to the latest from here (https://github.com/PolymerElements/generator-polymer-init-custom-build/blob/master/generators/app/gulpfile.js).

I'm not sure if the polymer-cli update was necessary but it was the first thing I did so I can't say for sure.

**Comment by FredKSchott** [comment] 2017-03-20 23:01
Interesting, @usergenic has been working on some other Windows fixes that were just released in v0.9.1. Updating to that may fix this specific issue as well

I'll create a PR

**Comment by FredKSchott** [comment] 2017-03-21 16:27
Just updated in the PR referenced above, mind updating in your project as well and seeing if that fixes things?

**Comment by hyyan** [comment] 2017-04-10 14:38
Any news about this issue ?

**Comment by stramel** [comment] 2017-05-16 02:30
@hyyan I believe this has been fixed.

**Closed** 2017-05-24 17:55 UTC
